194 transfer scheduler to separate container
Studio-Yandex-Practicum/sobitie pull request #213
Opened 2023-11-24 15:33 UTC by Todvaa

2023-11-24 21:27 UTC, NiKuma0 requested changes

2023-11-24 21:27 UTC, NiKuma0 commented on docker-compose.yaml
> +#      context: .
Комментарии убери.

2023-11-24 21:27 UTC, NiKuma0 commented on drf_sobitie/vk_utils/management/commands/start-scheduler.py
> +            )
А зачем тут несколько раз логгер конфигурируем?

2023-11-24 21:27 UTC, NiKuma0 commented on requirements.txt
В дургом ПР уже сделали, теперь у тебя кофликт.

2023-11-24 21:27 UTC, NiKuma0 commented on docker-compose.yaml
> +      - bot
бот можно не ждать.

2023-11-24 21:27 UTC, NiKuma0 commented on docker-compose.yaml
> +      - data:/app/drf_sobitie/db
Scheduler-у точно нужны эти данные? Он не должен зависеть от статики и БД.

2023-11-24 21:27 UTC, NiKuma0 commented on Dockerfile
> +RUN pip install -e .
Оставь как было. Зачем убрал, не работает?

Мы выше устанавливаем зависимости. `-e` - это для разработки.

2023-11-24 21:27 UTC, NiKuma0 commented on .env-example
> +VK_APP_SERVICE_KEY=
Не очень понятно, почему у нас изменились переменные?

2023-11-24 22:49 UTC, Todvaa commented on .env-example
> +VK_APP_SERVICE_KEY=
Более понятный контекст, раньше был VK_SERVICE_KEY и он использовался и в longpoll и в scheduler при том что там методы требующие разные токены, потому теперь у нас две отдельные переменные

2023-11-24 22:52 UTC, Todvaa commented on Dockerfile
> +RUN pip install -e .
сейчас сработало, вернул

2023-11-24 22:54 UTC, Todvaa commented on docker-compose.yaml
> +#      context: .
ок

2023-11-24 22:55 UTC, Todvaa commented on requirements.txt
убрал

2023-11-24 22:55 UTC, Todvaa commented on drf_sobitie/vk_utils/management/commands/start-scheduler.py
> +            )
убрал

2023-11-24 22:55 UTC, Todvaa commented on docker-compose.yaml
> +      - bot
ок

2023-11-24 22:55 UTC, Todvaa commented on docker-compose.yaml
> +      - data:/app/drf_sobitie/db
убрал

2023-11-27 16:47 UTC, NiKuma0 approved these changes

2023-11-27 16:47 UTC, merged